apiVersion: v1 
kind: Namespace
metadata:
  name: khyme-system 
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: frontend-pod # base Pod name
  namespace: khyme-system 
spec:
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend # Selector for Pod name search.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      containers:
        # frontend container configuration
      - name: frontend
        # gets patched to the specific docker image name in cluster/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: frontend-image
        imagePullPolicy: IfNotPresent
        # define ports to expose;
        # service definition 'frontend-service', below, actually exposes these ports
        ports:
        - name: frontend
          containerPort: 3000 
        env:
          - name: KUBERNETES_NAMESPACE 
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODENAME 
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: v1 
kind: Service 
metadata:
  name: frontend-service 
  namespace: khyme-system
spec:
  type: ClusterIP
  selector:
    app: frontend 
  ports:
  - name: frontend 
    port: 3000
    targetPort: frontend
        