apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- ./phaction-patch.yaml
images:
- name: frontend-image
  newName: jnkroeker/phaction-frontend
  newTag: 0.0.11
