apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: frontend-pod 
  namespace: khyme-system 
spec:
  replicas: 1 
  strategy:
    type: Recreate 
  selector: 
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend 
    spec:
      containers:
      - name: frontend 
      # tasker container configuration
        resources: 
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full core